name: project_name
packages:
  - "apps/**"
  - "packages/**"
  - "*"

scripts:
  prepare:
    run: melos bootstrap && melos run build

  analyze:
    run: melos exec -- "flutter analyze"
    description: Run `flutter analyze` in all packages
  
  format:
    run: melos exec -- "flutter format"
    description: Run `flutter format` in all packages

  test:dart:
    description: Run selective unit tests
    exec: dart test --no-pub --coverage
    packageFilters:
      flutter: false
      dir-exists: "test"
      fail-fast: true

  test:flutter:
    exec: flutter test --no-pub --coverage
    packageFilters:
      flutter: true
      dir-exists: test

  test:
    run: melos run test:flutter --no-select && melos run test:dart --no-select && melos run gen_coverage
    description: Run all Flutter tests in this project.

  gen_coverage: melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh"

command:
  bootstrap:
    usePubspecOverrides: true